<?php

namespace AppBundle\Repository;

/**
 * MdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MdpRepository extends \Doctrine\ORM\EntityRepository
{
}
